language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

# environment variables
env:

  global:
    - CC_TEST_REPORTER_ID=6d3379169de0e2a1a780f93c8f0545849b6227531f6f891b3da576b1ff24624c
    - DJANGO_ENV=Testing
  
  #- DJANGO_ENV=Testing


# command to install dependencies
install:
  - pip install -r requirements.txt

# start postgres in travis
services:
  - postgresql

# create database
before_script:
  - psql -c 'create database ah_backend;' -U postgres
  - psql -c 'CREATE TABLE auth_group (
      id SERIAL PRIMARY KEY,
      name character varying(80) NOT NULL UNIQUE
  );'
  
  - psql -c 'CREATE TABLE authentication_user (
      id SERIAL PRIMARY KEY,
      password character varying(128) NOT NULL,
      last_login timestamp with time zone,
      is_superuser boolean NOT NULL,
      username character varying(255) NOT NULL UNIQUE,
      email character varying(254) NOT NULL UNIQUE,
      is_active boolean NOT NULL,
      is_staff boolean NOT NULL,
      created_at timestamp with time zone NOT NULL,
      updated_at timestamp with time zone NOT NULL
  );'
  
  - python manage.py makemigrations
  - python manage.py migrate


# command to run tests
script:
  - coverage run --source=authors manage.py test

  - python manage.py test

  - COVERALLS_REPO_TOKEN="ujioY6o1FFgyYOEeb7Kl0O4yX06KxyLxe" coveralls

  # - python manage.py test


after-success:
  coveralls




